repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
# -   repo: https://github.com/PyCQA/isort
#     rev: 5.13.2
#     hooks:
#     -   id: isort
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        args: ["--config=.black"]
